name: C++ Compilation & Tests (Manual Only)

on:
  workflow_dispatch:   # Enables Run Workflow button only  
    branches: [ main ] # Only appears when main branch is selected

jobs:

  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile C++ code
      run: |
        g++ -std=c++17 -Wall -Werror math.cpp -c
        g++ -std=c++17 math.o -o app
        echo "Compilation successful!"

  test:
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GoogleTest
      run: |
        sudo apt update
        sudo apt install -y libgtest-dev cmake
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Build tests
      run: |
        g++ -std=c++17 -I. -c math.cpp
        g++ -std=c++17 -I. -c test_math.cpp
        g++ math.o test_math.o -lgtest -lgtest_main -pthread -o tests

    - name: Run tests
      run: ./tests
